
import Image from "next/image";
import Link from "next/link";
import OwnerBottomNav from "@/components/OwnerBottomNav";
import {getOwnerPortalData} from "@/lib/owner-data";

export default async function Owner(){
  const data=await getOwnerPortalData();
  if(!data.authorized)return <div className="shell owner-shell"><header className="topbar"><Image src="/kch-logo.png" alt="KadaCourtHub" width={340} height={130} className="logo" priority/><Link href="/home" className="muted">Player View</Link></header><main className="content owner-content"><p className="eyebrow">COMMISSIONER</p><h1 className="title">Conference Management</h1><section className="card owner-access"><h2>Commissioner access required</h2><p className="muted">This area is available only to a conference commissioner. Ask the current commissioner to add the commissioner role to your conference membership.</p><Link href="/home" className="btn primary">Return to Player View</Link></section></main></div>;
  const hour=Number(new Intl.DateTimeFormat("en-US",{timeZone:data.timezone,hour:"2-digit",hourCycle:"h23"}).formatToParts(new Date()).find(part=>part.type==="hour")?.value??0);
  const greeting=hour<12?"Good morning":hour<18?"Good afternoon":"Good night";
  const lastName=data.ownerName.trim().split(/\s+/).at(-1)??"Owner";
  const activeSeason=data.seasons.find(season=>!season.canceledAt&&season.setupStage<7);
  const games=data.seasons.filter(season=>!season.canceledAt).flatMap(season=>season.games);
  const missingScores=data.seasons.filter(season=>!season.canceledAt&&season.setupStage>=7).flatMap(season=>season.games).filter(game=>game.status==="scheduled"&&new Date(game.startsAt)<=new Date()&&(game.homeScore===null||game.awayScore===null)).length;
  const pendingPayments=data.paymentSubmissions.filter(submission=>submission.status==="pending").length;
  const balancesDue=data.paymentGroups.flatMap(group=>group.players).filter(player=>player.due>0).length;
  const pendingRosterRequests=data.rosterRequests.filter(request=>request.status==="pending").length;
  const scheduleNeedsAttention=Boolean(activeSeason&&activeSeason.setupStage<7);
  const activeVisualStep=activeSeason?(activeSeason.setupStage<=3?activeSeason.setupStage+1:activeSeason.setupStage===4?(activeSeason.preseasonReady?6:5):activeSeason.setupStage===5?7:8):1;
  const setupStepNames=["Create Season","Add Divisions","Add Teams","Assign Captains","Fees & Uniforms","Invite Players","Draft Rosters","Build Schedule"];
  const seasonDetail=activeSeason?`${data.conferenceName} · Step ${activeVisualStep} — ${setupStepNames[activeVisualStep-1]}`:data.conferenceName;
  return <div className="shell owner-shell guided-owner-shell"><header className="topbar"><Image src="/kch-logo.png" alt="KadaCourtHub" width={340} height={130} className="logo" priority/></header><main className="content owner-content owner-dashboard"><p className="eyebrow">CONFERENCE COMMISSIONER</p><h1 className="title">{greeting}, Mr. {lastName}!</h1><p className="owner-dashboard-question">What would you like to do?</p><nav className="owner-action-grid" aria-label="Conference commissioner actions"><Link href="/owner/setup" className="owner-action-card season-action"><span className="owner-action-icon">＋</span>{activeSeason&&<i className="owner-action-dot" aria-label="Season setup needs attention"/>}<div><small>SEASON</small><b>Create Season Tournament</b><p>{seasonDetail}</p></div></Link><Link href="/owner/roster" className="owner-action-card"><span className="owner-action-icon">♙</span>{pendingRosterRequests>0&&<i className="owner-action-dot" aria-label="Player Directory has roster requests waiting"/>}<div><small>PLAYER DIRECTORY</small><b>Manage conference players</b><p>Invite, assign and change roster.</p></div></Link><Link href="/owner/schedule" className="owner-action-card"><span className="owner-action-icon">▦</span>{scheduleNeedsAttention&&<i className="owner-action-dot" aria-label="Schedule setup needs attention"/>}<div><small>SCHEDULE</small><b>View or update schedule</b><p>{games.length?`${games.length} total scheduled game${games.length===1?"":"s"}`:"No schedule has been created yet"}</p></div></Link><Link href="/owner/scores" className="owner-action-card owner-featured-action"><span className="owner-action-icon">⌁</span>{missingScores>0&&<i className="owner-action-dot" aria-label="Scores need attention"/>}<div><small>SCORES</small><b>Update game results</b><p>{missingScores?`${missingScores} completed game${missingScores===1?"":"s"} need results`:"No completed games are awaiting scores"}</p></div></Link><Link href="/owner/payments" className="owner-action-card owner-featured-action"><span className="owner-action-icon">▣</span>{pendingPayments>0&&<i className="owner-action-dot" aria-label="Payments need attention"/>}<div><small>PAYMENTS</small><b>{balancesDue} balance{balancesDue===1?"":"s"} due</b><p>Review payments and balances.</p></div></Link><Link href="/owner/financials" className="owner-action-card financial-action"><span className="owner-action-icon">＄</span><div><small>FINANCIAL SUMMARY</small><b>Track profit and loss</b><p>Income and expense report.</p></div></Link></nav></main><OwnerBottomNav active="home"/></div>;
}
