"use client";

import {useActionState,useState} from "react";
import {saveDraftPlayerAction,submitTeamRosterAction,updateDraftPlayerAction,type CaptainActionState} from "@/app/captain/actions";
import type {CaptainPortalData} from "@/lib/captain-data";

const initial:CaptainActionState={};
function Notice({state}:{state:CaptainActionState}){return <>{state.error&&<p className="form-error">{state.error}</p>}{state.message&&<p className="form-success">{state.message}</p>}</>}

function DraftedPlayer({teamId,player,locked}:{teamId:string;player:CaptainPortalData["roster"][number];locked:boolean}){
  const[state,action,pending]=useActionState(updateDraftPlayerAction,initial);
  return <details className="captain-roster-player"><summary><span><b>{player.name}</b><small>#{player.jerseyNumber??"—"} · {player.position||"Position needed"}</small></span><strong>›</strong></summary><form action={action} className="owner-form"><input type="hidden" name="teamId" value={teamId}/><input type="hidden" name="registrationId" value={player.registrationId}/><div className="compact-fields"><label>Jersey<input name="jerseyNumber" type="number" min="0" max="99" defaultValue={player.jerseyNumber??""}/></label><label>Position<select name="position" defaultValue={player.position}><option value="">Choose position</option>{["G","SG","PG","F","PF","C"].map(position=><option key={position} value={position}>{position}</option>)}</select></label><label>Uniform size<select name="uniformSize" defaultValue={player.uniformSize}><option value="">Not set</option>{["S","M","L","XL","2XL","3XL"].map(size=><option key={size} value={size}>{size}</option>)}</select></label></div><Notice state={state}/><div className="draft-review-actions"><button className="btn secondary" name="remove" value="yes" disabled={pending||locked}>Remove</button><button className="btn primary" disabled={pending||locked}>Save Player</button></div></form></details>;
}

export default function CaptainDraftRoster({data}:{data:CaptainPortalData}){
  const[query,setQuery]=useState(""),[selected,setSelected]=useState("");
  const[addState,addAction,addPending]=useActionState(saveDraftPlayerAction,initial),[submitState,submitAction,submitPending]=useActionState(submitTeamRosterAction,initial);
  const locked=data.draftStatus==="submitted"||data.draftStatus==="approved",players=data.roster.filter(player=>player.registrationId!==data.activeRegistrationId&&!['Captain','Co-captain'].includes(player.role)),availableCandidates=data.candidates.filter(candidate=>!data.roster.some(player=>player.registrationId===candidate.registrationId));
  const matches=query.trim().length<2?availableCandidates.slice(0,8):availableCandidates.filter(candidate=>candidate.name.toLowerCase().includes(query.trim().toLowerCase())).slice(0,8);
  return <section className="card owner-section captain-draft-entry"><div className="owner-section-title"><span className="owner-icon">🏀</span><span><h2>Enter Drafted Players</h2><p>Use the paper draft sheet, then add jersey, position, and uniform size here.</p></span></div><div className={`captain-draft-status ${data.draftStatus}`}><b>{data.draftStatus.replace("_"," ")}</b><span>{data.draftStatus==="submitted"?"Locked while the owner reviews it.":data.draftStatus==="approved"?"Approved and ready for roster publication.":data.draftStatus==="changes_requested"?(data.ownerNote||"The owner requested roster changes. Update the players, then resubmit for approval."):"Complete your team, then send it to the owner."}</span></div><section className="captain-added-players"><div><h3>Added players</h3><span>{players.length} on this roster</span></div><div className="captain-roster-list">{players.map(player=><DraftedPlayer key={player.registrationId} teamId={data.teamId} player={player} locked={locked}/>)}{!players.length&&<p className="empty-note">No drafted players entered yet.</p>}</div></section>{!locked&&<form action={addAction} className="owner-form captain-player-search"><input type="hidden" name="teamId" value={data.teamId}/><input type="hidden" name="invitationId" value={selected}/><label>Add another player<input value={query} onChange={event=>{setQuery(event.target.value);setSelected("")}} placeholder="Type player name"/></label>{matches.length>0&&<div className="leader-search-results">{matches.map(candidate=><button key={candidate.invitationId} type="button" onClick={()=>{setSelected(candidate.invitationId);setQuery(candidate.name)}}><b>{candidate.name}</b><small>{candidate.selectionStatus}</small></button>)}</div>}<div className="compact-fields"><label>Jersey number<input name="jerseyNumber" type="number" min="0" max="99"/></label><label>Position<select name="position" defaultValue=""><option value="">Choose position</option>{["G","SG","PG","F","PF","C"].map(position=><option key={position} value={position}>{position}</option>)}</select></label><label>Uniform size<select name="uniformSize" defaultValue=""><option value="">Not set</option>{["S","M","L","XL","2XL","3XL"].map(size=><option key={size} value={size}>{size}</option>)}</select></label></div><Notice state={addState}/><button className="btn primary" disabled={addPending||!selected}>{addPending?"Adding…":"Add to My Team"}</button></form>}{!locked&&<form action={submitAction} className="owner-form captain-submit-roster"><input type="hidden" name="teamId" value={data.teamId}/><Notice state={submitState}/><button className="btn primary" disabled={submitPending||!players.length}>{submitPending?"Sending…":data.draftStatus==="changes_requested"?"Resubmit Updated Roster":"Submit Team Roster to Owner"}</button><small>Submitting locks this roster until the owner approves it or requests changes.</small></form>}</section>;
}
